// src/components/CardDetail.tsx
import React from 'react';
import { useNavigate } from 'react-router-dom';
import { Card, CardHeader, CardTitle, CardContent, } from '@/components/ui/card' ;
import { Button } from '@/components/ui/button' ;

interface CardDetailProps {
  title: string;
  content: string;
}

const CardDetail: React.FC<CardDetailProps> = ({ title, content }) => {
  const navigate = useNavigate();
  return (
    <Card className="bg-[#0D1317] text-white border border-gray-700 shadow-md">
      <CardHeader>
        <CardTitle className="text-white">{title}</CardTitle>
      </CardHeader>
      <CardContent>
        <p className="text-white mb-4">{content}</p>
        <Button className="bg-[#101D42] hover:bg-[#232ED1] text-white" onClick={() => navigate(`/`)}>Voltar</Button>
      </CardContent>
    </Card>
  );
};

export default CardDetail;

// src/components/CardDetail.vue
<script setup lang="ts">
import { defineProps } from 'vue';
import { useRouter } from 'vue-router';
import {Card} from "primevue";

const props = defineProps<{
  title: string;
  content: string;
}>();

const router = useRouter();

function goBack() {
  router.push('/');
}
</script>

<template>
  <Card
      class="shadow-md p-4 rounded"
      style="background-color: #0D1317; color: white; border: 1px solid #374151;"
  >
    <template #title>
      <h3 class="text-xl font-bold">{{ title }}</h3>
    </template>
    <template #content>
      <p class="mb-4">{{ content }}</p>
      <button
          class="bg-[#101D42] hover:bg-[#232ED1] text-white py-2 px-4 rounded"
          @click="goBack"
      >
        Voltar
      </button>
    </template>
  </Card>
</template>

<style scoped>
</style>
